//! Panel hardware, drawn instead of painted.
//!
//! The knobs are generated by PultEQFx's `assetgen` from parametric geometry
//! and rendered under one fixed light, so a knob's highlight stays where the
//! light is when the knob turns. The static parts are still cut-out
//! photographs, which never reveal that because they never move. Rotating ones
//! are drawn through a canvas transform, about the shaft rather than about the
//! middle of the image.
//!
//! An image belongs to the canvas that uploaded it, and a second instance of
//! the plugin gets a second canvas, so each widget uploads and caches its own
//! rather than sharing one through a global.

use nih_plug_vizia::vizia::prelude::Canvas;
use nih_plug_vizia::vizia::vg;
use std::cell::Cell;

use super::style::SWEEP;

pub const KNOB_LARGE: &[u8] = include_bytes!("../../../assets/gen/knob_large.png");
pub const KNOB_SMALL: &[u8] = include_bytes!("../../../assets/gen/knob_small.png");
pub const CAP_OUT: &[u8] = include_bytes!("../../../assets/cap_out.png");
pub const CAP_IN: &[u8] = include_bytes!("../../../assets/cap_in.png");
pub const VU: &[u8] = include_bytes!("../../../assets/vu.png");

/// The four mounting screws, each photographed already driven to its own
/// angle. Nothing is rotated here: a screw sits where it was tightened, and
/// turning one image would carry its lighting round with it.
pub const SCREWS: [&[u8]; 4] = [
    include_bytes!("../../../assets/screw_1.png"),
    include_bytes!("../../../assets/screw_2.png"),
    include_bytes!("../../../assets/screw_3.png"),
    include_bytes!("../../../assets/screw_4.png"),
];

/// Where the indicator points in each render, in degrees clockwise from twelve
/// o'clock. The renders are square and centred on the shaft with the indicator
/// already at twelve, so there is nothing left to calibrate.
pub const KNOB_LARGE_REST: f32 = 0.0;
pub const KNOB_SMALL_REST: f32 = 0.0;
pub const CENTRE: (f32, f32) = (0.5, 0.5);

/// A rotating control cannot be drawn by turning one image: that turns its
/// lighting with it, so the highlight travels round the knob instead of
/// staying where the panel light is. Each frame is rendered separately with
/// the light fixed, and drawing picks one.
pub const KNOB_FRAMES: usize = 48;
pub const KNOB_ARC: f32 = SWEEP;

/// The meter's geometry, measured off the photograph rather than estimated.
///
/// Two separate circles are involved. The needle turns about the brass hub,
/// but the scale is struck about a different and much larger circle whose
/// centre falls well below the case -- fitting the printed arc puts it at
/// 1.29 times the height, against the hub at 0.76. So the needle cannot sweep
/// a fixed angle and land on the marks: it has to be aimed at the mark it is
/// meant to be pointing at, which is what `vu_mark` does.
///
/// Everything is a fraction of the drawn rectangle, and the two radii are
/// given separately, because the panel draws the meter wider than the
/// photograph's own proportions and the arc becomes an ellipse.
pub const VU_HUB: (f32, f32) = (0.4943, 0.7636);
const VU_ARC_CENTRE: (f32, f32) = (0.5106, 1.2864);
const VU_ARC_RADIUS: (f32, f32) = (0.6519, 0.9553);
/// The arc's own angular extent, in degrees, from the -20 mark to the +3.
const VU_ARC_ENDS: (f32, f32) = (-29.68, 30.61);
/// What the two ends of the printed scale read.
pub const VU_MIN_DB: f32 = -20.0;
pub const VU_MAX_DB: f32 = 3.0;

/// How far along the scale a reading sits, from 0 at the left end to 1 at the
/// right.
///
/// A moving coil deflects with the voltage through it, not with its logarithm,
/// so the marks on a VU face are spaced logarithmically: the gap from -20 to
/// -10 is a fifth of the gap from -3 to 0. Reading the scale as though it were
/// linear in dB, which is what this used to do, puts the needle nowhere near
/// the number it is supposed to be indicating.
pub fn vu_position(db: f32) -> f32 {
    let lo = 10f32.powf(VU_MIN_DB / 20.0);
    let hi = 10f32.powf(VU_MAX_DB / 20.0);
    ((10f32.powf(db / 20.0) - lo) / (hi - lo)).clamp(0.0, 1.0)
}

/// The point on the printed arc a given position along the scale lands on, in
/// the drawn rectangle's own coordinates.
pub fn vu_mark(x: f32, y: f32, w: f32, h: f32, position: f32) -> (f32, f32) {
    let ends = VU_ARC_ENDS;
    let a = (ends.0 + position.clamp(0.0, 1.0) * (ends.1 - ends.0)).to_radians();
    (
        x + w * (VU_ARC_CENTRE.0 + VU_ARC_RADIUS.0 * a.sin()),
        y + h * (VU_ARC_CENTRE.1 - VU_ARC_RADIUS.1 * a.cos()),
    )
}

/// Where and how large to draw a photograph, and about which point to turn
/// it. Grouped rather than passed as a row of bare numbers, because they are
/// all lengths and angles and easy to transpose.
#[derive(Clone, Copy)]
pub struct Placement {
    /// Where the shaft goes.
    pub x: f32,
    pub y: f32,
    /// Drawn height; the width follows the photograph's proportions.
    pub height: f32,
    /// Clockwise from twelve o'clock.
    pub degrees: f32,
    /// The shaft's position within the photograph.
    pub pivot: (f32, f32),
}

/// A lazily uploaded image. The canvas is only reachable from `draw`, so the
/// upload happens on the first frame and the id is kept from then on.
#[derive(Default)]
pub struct Sprite {
    id: Cell<Option<vg::ImageId>>,
}

impl Sprite {
    pub const fn new() -> Self {
        Self {
            id: Cell::new(None),
        }
    }

    fn id(&self, canvas: &mut Canvas, bytes: &[u8]) -> Option<vg::ImageId> {
        if let Some(id) = self.id.get() {
            return Some(id);
        }
        // Mipmaps keep the controls from crawling when the window is scaled.
        match canvas.load_image_mem(bytes, vg::ImageFlags::GENERATE_MIPMAPS) {
            Ok(id) => {
                self.id.set(Some(id));
                Some(id)
            }
            Err(_) => None,
        }
    }

    /// Draws one frame of a vertical filmstrip with its shaft on a point.
    ///
    /// No rotation is applied: the frame was rendered at the angle wanted, so
    /// its highlights and shadow sit where the panel light put them.
    pub fn draw_frame(
        &self,
        canvas: &mut Canvas,
        bytes: &[u8],
        at: Placement,
        frame: usize,
        frames: usize,
    ) {
        let Some(id) = self.id(canvas, bytes) else {
            return;
        };
        let Ok((iw, ih)) = canvas.image_size(id) else {
            return;
        };
        let strip = frames.max(1);
        let frame = frame.min(strip - 1);
        let cell = ih as f32 / strip as f32;
        let scale = at.height / cell;
        let (w, h) = (iw as f32 * scale, cell * scale);

        canvas.save();
        canvas.translate(at.x - w * at.pivot.0, at.y - h * at.pivot.1);
        // The paint covers the whole strip, shifted so the wanted frame lands
        // on the rectangle being filled; the path clips away the rest.
        let mut path = vg::Path::new();
        path.rect(0.0, 0.0, w, h);
        canvas.fill_path(
            &path,
            &vg::Paint::image(
                id,
                0.0,
                -(frame as f32) * h,
                w,
                h * strip as f32,
                0.0,
                1.0,
            ),
        );
        canvas.restore();
    }

    /// Draws the photograph with its shaft on a point, turned by `degrees`.
    pub fn draw(&self, canvas: &mut Canvas, bytes: &[u8], at: Placement) {
        let Some(id) = self.id(canvas, bytes) else {
            return;
        };
        let Ok((iw, ih)) = canvas.image_size(id) else {
            return;
        };
        let scale = at.height / ih as f32;
        let (w, h) = (iw as f32 * scale, ih as f32 * scale);

        canvas.save();
        canvas.translate(at.x, at.y);
        canvas.rotate(at.degrees.to_radians());
        canvas.translate(-w * at.pivot.0, -h * at.pivot.1);
        let mut path = vg::Path::new();
        path.rect(0.0, 0.0, w, h);
        canvas.fill_path(&path, &vg::Paint::image(id, 0.0, 0.0, w, h, 0.0, 1.0));
        canvas.restore();
    }

    /// Draws it upright, stretched to fill a rectangle.
    pub fn draw_rect(&self, canvas: &mut Canvas, bytes: &[u8], x: f32, y: f32, w: f32, h: f32) {
        let Some(id) = self.id(canvas, bytes) else {
            return;
        };
        let mut path = vg::Path::new();
        path.rect(x, y, w, h);
        canvas.fill_path(&path, &vg::Paint::image(id, x, y, w, h, 0.0, 1.0));
    }
}

impl Sprite {
    /// Draws a switch cap in its bezel. The photographed caps come in two
    /// colours, and the pressed one also sits lower in its bezel.
    pub fn draw_button(
        &self,
        canvas: &mut Canvas,
        b: nih_plug_vizia::vizia::prelude::BoundingBox,
        scale: f32,
        pressed: bool,
    ) {
        // The bezel stands off the panel, so it throws a shadow of its own.
        // Without it the bank of switches reads as four rectangles painted on
        // rather than four caps standing proud of it.
        crate::editor::style::cast_shadow(canvas, b, scale, 4.0, 3.0 * scale);

        // The bezel the cap travels in.
        let mut well = vg::Path::new();
        well.rounded_rect(b.x, b.y, b.w, b.h, 3.0 * scale);
        canvas.fill_path(
            &well,
            &vg::Paint::linear_gradient(
                b.x,
                b.y,
                b.x,
                b.y + b.h,
                vg::Color::rgb(0x08, 0x08, 0x0a),
                vg::Color::rgb(0x1a, 0x1a, 0x1e),
            ),
        );

        let travel = if pressed { 2.5 * scale } else { 0.0 };
        let inset = 3.0 * scale;
        let x = b.x + inset;
        let y = b.y + inset + travel;
        let w = b.w - inset * 2.0;
        let h = b.h - inset * 2.0 - travel;

        if !pressed {
            let mut shadow = vg::Path::new();
            shadow.rounded_rect(x, y + 2.0 * scale, w, h, 2.0 * scale);
            let mut ink = vg::Color::black();
            ink.set_alphaf(0.6);
            canvas.fill_path(&shadow, &vg::Paint::color(ink));
        }

        let bytes = if pressed { CAP_IN } else { CAP_OUT };
        self.draw_rect(canvas, bytes, x, y, w, h);
    }
}
