//! Panel hardware, drawn instead of painted.
//!
//! The knobs are generated by PultEQFx's `assetgen` from parametric geometry
//! and rendered under one fixed light, so a knob's highlight stays where the
//! light is when the knob turns. The static parts are still cut-out
//! photographs, which never reveal that because they never move. Rotating ones
//! are drawn through a canvas transform, about the shaft rather than about the
//! middle of the image.
//!
//! Each widget decodes and caches its own images rather than sharing them
//! through a global. That was forced under femtovg, where an image belonged to
//! the canvas that uploaded it and a second instance of the plugin had a
//! second canvas; Skia's decoded images are not tied to a canvas, but keeping
//! them per widget keeps two instances from sharing anything at all. A
//! [`Sprite`] is tied to one image when it is made: a cache that took its
//! image as an argument on every draw kept whichever it saw first and quietly
//! drew that for the other, which is how the switch caps never changed colour
//! when pressed.

use super::paint::{self as vg, PanelCanvas};
use std::cell::OnceCell;
use vizia_plug::vizia::prelude::{BoundingBox, Canvas};
use vizia_plug::vizia::vg as sk;

pub const KNOB_LARGE: &[u8] = include_bytes!("../../../assets/gen/knob_large.png");
pub const KNOB_SMALL: &[u8] = include_bytes!("../../../assets/gen/knob_small.png");
pub const CAP_OUT: &[u8] = include_bytes!("../../../assets/cap_out.png");
pub const CAP_IN: &[u8] = include_bytes!("../../../assets/cap_in.png");
pub const VU: &[u8] = include_bytes!("../../../assets/vu.png");

/// The four mounting screws, each photographed already driven to its own
/// angle. Nothing is rotated here: a screw sits where it was tightened, and
/// turning one image would carry its lighting round with it.
pub const SCREWS: [&[u8]; 4] = [
    include_bytes!("../../../assets/screw_1.png"),
    include_bytes!("../../../assets/screw_2.png"),
    include_bytes!("../../../assets/screw_3.png"),
    include_bytes!("../../../assets/screw_4.png"),
];

/// The shaft's position in every render: square, and centred on it.
pub const CENTRE: (f32, f32) = (0.5, 0.5);

/// A rotating control cannot be drawn by turning one image: that turns its
/// lighting with it, so the highlight travels round the knob instead of
/// staying where the panel light is. Each frame is rendered separately with
/// the light fixed, and drawing picks one.
pub const KNOB_FRAMES: usize = 48;

/// The meter's geometry, measured off the photograph rather than estimated.
///
/// Two separate circles are involved. The needle turns about the brass hub,
/// but the scale is struck about a different and much larger circle whose
/// centre falls well below the case -- fitting the printed arc puts it at
/// 1.29 times the height, against the hub at 0.76. So the needle cannot sweep
/// a fixed angle and land on the marks: it has to be aimed at the mark it is
/// meant to be pointing at, which is what `vu_mark` does.
///
/// Everything is a fraction of the drawn rectangle, and the two radii are
/// given separately, because the panel draws the meter wider than the
/// photograph's own proportions and the arc becomes an ellipse.
pub const VU_HUB: (f32, f32) = (0.4943, 0.7636);
const VU_ARC_CENTRE: (f32, f32) = (0.5106, 1.2864);
const VU_ARC_RADIUS: (f32, f32) = (0.6519, 0.9553);
/// The arc's own angular extent, in degrees, from the -20 mark to the +3.
const VU_ARC_ENDS: (f32, f32) = (-29.68, 30.61);
/// What the two ends of the printed scale read.
pub const VU_MIN_DB: f32 = -20.0;
pub const VU_MAX_DB: f32 = 3.0;

/// How far along the scale a reading sits, from 0 at the left end to 1 at the
/// right.
///
/// A moving coil deflects with the voltage through it, not with its logarithm,
/// so the marks on a VU face are spaced logarithmically: the gap from -20 to
/// -10 is a fifth of the gap from -3 to 0. Reading the scale as though it were
/// linear in dB, which is what this used to do, puts the needle nowhere near
/// the number it is supposed to be indicating.
pub fn vu_position(db: f32) -> f32 {
    let lo = 10f32.powf(VU_MIN_DB / 20.0);
    let hi = 10f32.powf(VU_MAX_DB / 20.0);
    ((10f32.powf(db / 20.0) - lo) / (hi - lo)).clamp(0.0, 1.0)
}

/// The point on the printed arc a given position along the scale lands on, in
/// the drawn rectangle's own coordinates.
pub fn vu_mark(x: f32, y: f32, w: f32, h: f32, position: f32) -> (f32, f32) {
    let ends = VU_ARC_ENDS;
    let a = (ends.0 + position.clamp(0.0, 1.0) * (ends.1 - ends.0)).to_radians();
    (
        x + w * (VU_ARC_CENTRE.0 + VU_ARC_RADIUS.0 * a.sin()),
        y + h * (VU_ARC_CENTRE.1 - VU_ARC_RADIUS.1 * a.cos()),
    )
}

/// Where and how large to draw a photograph, and about which point to turn
/// it. Grouped rather than passed as a row of bare numbers, because they are
/// all lengths and angles and easy to transpose.
#[derive(Clone, Copy)]
pub struct Placement {
    /// Where the shaft goes.
    pub x: f32,
    pub y: f32,
    /// Drawn height; the width follows the photograph's proportions.
    pub height: f32,
    /// Clockwise from twelve o'clock.
    pub degrees: f32,
    /// The shaft's position within the photograph.
    pub pivot: (f32, f32),
}

/// One image, decoded lazily. The canvas is only reachable from `draw`, so
/// the decode happens on the first frame and the image is kept from then on.
pub struct Sprite {
    bytes: &'static [u8],
    image: OnceCell<Option<sk::Image>>,
}

/// Mipmaps keep the controls from crawling when the window is scaled.
fn sampling() -> sk::SamplingOptions {
    sk::SamplingOptions::new(sk::FilterMode::Linear, sk::MipmapMode::Linear)
}

impl Sprite {
    pub const fn new(bytes: &'static [u8]) -> Self {
        Self {
            bytes,
            image: OnceCell::new(),
        }
    }

    fn image(&self) -> Option<&sk::Image> {
        self.image
            .get_or_init(|| sk::Image::from_encoded(sk::Data::new_copy(self.bytes)))
            .as_ref()
    }

    /// Draws one frame of a vertical filmstrip with its shaft on a point.
    ///
    /// No rotation is applied: the frame was rendered at the angle wanted, so
    /// its highlights and shadow sit where the panel light put them.
    pub fn draw_frame(&self, canvas: &Canvas, at: Placement, frame: usize, frames: usize) {
        let Some(image) = self.image() else {
            return;
        };
        let (iw, ih) = (image.width() as f32, image.height() as f32);
        let strip = frames.max(1);
        let frame = frame.min(strip - 1);
        let cell = ih / strip as f32;
        let scale = at.height / cell;
        let (w, h) = (iw * scale, cell * scale);

        // Only the wanted frame is read, and strictly: the renders are framed
        // to the knob's silhouette, so the next frame starts right at its
        // edge and filtering across the boundary would pick up its rim.
        let source = sk::Rect::from_xywh(0.0, frame as f32 * cell, iw, cell);
        canvas.draw_image_rect_with_sampling_options(
            image,
            Some((&source, sk::canvas::SrcRectConstraint::Strict)),
            sk::Rect::from_xywh(at.x - w * at.pivot.0, at.y - h * at.pivot.1, w, h),
            sampling(),
            &sk::Paint::default(),
        );
    }

    /// Draws the photograph with its shaft on a point, turned by `degrees`.
    pub fn draw(&self, canvas: &Canvas, at: Placement) {
        let Some(image) = self.image() else {
            return;
        };
        let scale = at.height / image.height() as f32;
        let (w, h) = (image.width() as f32 * scale, image.height() as f32 * scale);

        canvas.save();
        canvas.translate((at.x, at.y));
        canvas.rotate(at.degrees, None);
        canvas.draw_image_rect_with_sampling_options(
            image,
            None,
            sk::Rect::from_xywh(-w * at.pivot.0, -h * at.pivot.1, w, h),
            sampling(),
            &sk::Paint::default(),
        );
        canvas.restore();
    }

    /// Draws it upright, stretched to fill a rectangle.
    pub fn draw_rect(&self, canvas: &Canvas, x: f32, y: f32, w: f32, h: f32) {
        let Some(image) = self.image() else {
            return;
        };
        canvas.draw_image_rect_with_sampling_options(
            image,
            None,
            sk::Rect::from_xywh(x, y, w, h),
            sampling(),
            &sk::Paint::default(),
        );
    }
}

/// A switch cap, photographed out and in. Two sprites, because they are two
/// images.
pub struct Cap {
    out: Sprite,
    pressed: Sprite,
}

impl Cap {
    pub const fn new() -> Self {
        Self {
            out: Sprite::new(CAP_OUT),
            pressed: Sprite::new(CAP_IN),
        }
    }

    /// Draws the cap in its bezel. The photographed caps come in two colours,
    /// and the pressed one also sits lower in its bezel.
    pub fn draw(&self, canvas: &Canvas, b: BoundingBox, scale: f32, pressed: bool) {
        // The bezel stands off the panel, so it throws a shadow of its own.
        // Without it the bank of switches reads as four rectangles painted on
        // rather than four caps standing proud of it.
        crate::editor::style::cast_shadow(canvas, b, scale, 4.0, 3.0 * scale);

        // The bezel the cap travels in.
        let mut well = vg::Path::new();
        well.rounded_rect(b.x, b.y, b.w, b.h, 3.0 * scale);
        canvas.fill_path(
            &well,
            &vg::Paint::linear_gradient(
                b.x,
                b.y,
                b.x,
                b.y + b.h,
                super::style::rgb(0x08080a),
                super::style::rgb(0x1a1a1e),
            ),
        );

        let travel = if pressed { 2.5 * scale } else { 0.0 };
        let inset = 3.0 * scale;
        let x = b.x + inset;
        let y = b.y + inset + travel;
        let w = b.w - inset * 2.0;
        let h = b.h - inset * 2.0 - travel;

        if !pressed {
            let mut shadow = vg::Path::new();
            shadow.rounded_rect(x, y + 2.0 * scale, w, h, 2.0 * scale);
            canvas.fill_path(
                &shadow,
                &vg::Paint::color(super::style::rgba(0x000000, 0.6)),
            );
        }

        let sprite = if pressed { &self.pressed } else { &self.out };
        sprite.draw_rect(canvas, x, y, w, h);
    }
}

impl Default for Cap {
    fn default() -> Self {
        Self::new()
    }
}
